- name: mysql
  hosts: mysql
  become: yes
  tasks:
  - name: disabling old mysql service
    ansible.builtin.shell: dnf module disable mysql -y

  - name: Setup the MySQL5.7 repo file
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: Install MySQL Server
    ansible.builtin.dnf:
      name: mysql-community-server
      state: present
  
  - name: Starting and Enabling mysql services
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: changing the default root password in order to start using the database service
    ansible.builtin.command:  mysql_secure_installation --set-root-pass RoboShop@1
